# See the available options: https://tdt-documentation.london.cloudapps.digital/configure_project/global_configuration/#configure-your-documentation-site

# Host to use for canonical URL generation (without trailing slash)
host: https://ministryofjustice.github.io/find-moj-data-user-guide

# Header-related options
show_govuk_logo: false
service_name: Find MoJ Data
service_link: https://find-moj-data.service.justice.gov.uk/
phase: PUBLIC BETA

# Links to show on right-hand-side of header
header_links:
  User guide home: /

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

show_contribution_banner: false
github_repo: ministryofjustice/find-moj-data-user-guide
github_branch: main

